### PR TITLE
Removed unnecessary duplicate code

### PR DESCRIPTION
**Pull request by combineads**
Signed-off-by: Byunghwa Yun ombine@combineads.co.kr

### CODE REVIEW

**Comment by rfecher** [comment]
good catch! it looks like thats been in there for awhile.

**Comment by rfecher** [comment]
@combineads  I'll need you to sign the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php) before I can merge.  Thanks!

**Comment by combineads** [comment]
@rfecher I've done. Thank you for your efforts.

**Comment by rfecher** [comment]
Thanks!

**Pull request merged**
